FROM python:3.11.3-slim-bullseye

WORKDIR /app

COPY ./pylintrc ./pylintrc
COPY ./.flake8 ./.flake8

COPY ./src ./src

COPY ./requirements.txt /app/
COPY ./requirements-dev.txt /app/

RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

RUN rm requirements.txt
RUN rm requirements-dev.txt