---
checks:
  # reliability
  priorityClassNotSet: warning
  # resources
  cpuRequestsMissing: danger
  cpuLimitsMissing: danger
  memoryRequestsMissing: danger
  memoryLimitsMissing: danger
  # images
  tagNotSpecified: warning
  pullPolicyNotAlways: warning
  # healthChecks
  readinessProbeMissing: warning
  livenessProbeMissing: warning
  # networking
  hostNetworkSet: warning
  hostPortSet: warning
  # security
  hostIPCSet: warning
  hostPIDSet: warning
  notReadOnlyRootFilesystem: warning
  privilegeEscalationAllowed: warning
  runAsRootAllowed: warning
  runAsPrivileged: warning
  dangerousCapabilities: danger
  insecureCapabilities: warning
  # custom
  resourceLimits: warning
  imageRegistry: warning

exemptions:
  - controllerNames:
      - my-network-controller
    rules:
      - hostNetworkSet
      - hostPortSet

customChecks:
  resourceLimits:
    containers:
      exclude:
        - initContainer
    successMessage: Resource limits are within the required range
    failureMessage: Resource limits should be within the required range
    category: Resources
    target: Container
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      required:
        - resources
      properties:
        resources:
          type: object
          required:
            - limits
          properties:
            limits:
              type: object
              required:
                - memory
                - cpu
              properties:
                memory:
                  type: string
                  resourceMinimum: 100M
                  resourceMaximum: 6G
                cpu:
                  type: string
                  resourceMinimum: 100m
                  resourceMaximum: "6"
  imageRegistry:
    successMessage: Image comes from allowed registries
    failureMessage: Image should not be from disallowed registry
    category: Images
    target: Container
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      properties:
        image:
          type: string
          pattern: cfmanteiga|ankane|digestojud|cloudsql-docker|busybox
