name: Publish to PyPI

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pypi-publish:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    environment:
      name: pypi
      url: https://pypi.org/p/{{cookiecutter.repository_name}}

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies
      run: make install

    - name: Tag and push version
      run: |
        TAG_VERSION="v$(uv version --short)"
        if git rev-parse "$TAG_VERSION" >/dev/null 2>&1; then
            echo "Tag already exists: $TAG_VERSION"
            echo "CREATED_TAG=false" >> $GITHUB_ENV
        else
            echo "Creating tag $TAG_VERSION ..."
            git tag "$TAG_VERSION"
            git push origin tag $TAG_VERSION
            echo "Tag $TAG_VERSION created and pushed with successfully!"

            echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
            echo "CREATED_TAG=true" >> $GITHUB_ENV
        fi

    - name: Echo enviroment variables created in runtime
      run: |
        echo "CREATED_TAG: ${{ env.CREATED_TAG }}"
        echo "TAG_VERSION: ${{ env.TAG_VERSION }}"

    - name: Create GitHub Release
      if: ${{ env.CREATED_TAG == 'true' }}
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.TAG_VERSION }}
        name: Release ${{ env.TAG_VERSION }}
        body: |
          ## Changes
          ${{ github.event.pull_request.body }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build package
      if: ${{ env.CREATED_TAG == 'true' }}
      run: uv build

    - name: Publish package
      if: ${{ env.CREATED_TAG == 'true' }}
      uses: pypa/gh-action-pypi-publish@release/v1

